/* Auto-generated by genmsg_cpp for file /home/ttremblay/groovy_workspace/sandbox/EposManager/msg/DigitalInputInfo.msg */
#ifndef EPOSMANAGER_MESSAGE_DIGITALINPUTINFO_H
#define EPOSMANAGER_MESSAGE_DIGITALINPUTINFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace EposManager
{
template <class ContainerAllocator>
struct DigitalInputInfo_ {
  typedef DigitalInputInfo_<ContainerAllocator> Type;

  DigitalInputInfo_()
  : node_id(0)
  , dIO_3_state(0)
  , dIO_4_state(0)
  , stamp()
  {
  }

  DigitalInputInfo_(const ContainerAllocator& _alloc)
  : node_id(0)
  , dIO_3_state(0)
  , dIO_4_state(0)
  , stamp()
  {
  }

  typedef uint16_t _node_id_type;
  uint16_t node_id;

  typedef uint8_t _dIO_3_state_type;
  uint8_t dIO_3_state;

  typedef uint8_t _dIO_4_state_type;
  uint8_t dIO_4_state;

  typedef ros::Time _stamp_type;
  ros::Time stamp;


  typedef boost::shared_ptr< ::EposManager::DigitalInputInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::EposManager::DigitalInputInfo_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DigitalInputInfo
typedef  ::EposManager::DigitalInputInfo_<std::allocator<void> > DigitalInputInfo;

typedef boost::shared_ptr< ::EposManager::DigitalInputInfo> DigitalInputInfoPtr;
typedef boost::shared_ptr< ::EposManager::DigitalInputInfo const> DigitalInputInfoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::EposManager::DigitalInputInfo_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::EposManager::DigitalInputInfo_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace EposManager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::EposManager::DigitalInputInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::EposManager::DigitalInputInfo_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::EposManager::DigitalInputInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0d37fc0461947d1bf0b6618aa2efcf0a";
  }

  static const char* value(const  ::EposManager::DigitalInputInfo_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0d37fc0461947d1bULL;
  static const uint64_t static_value2 = 0xf0b6618aa2efcf0aULL;
};

template<class ContainerAllocator>
struct DataType< ::EposManager::DigitalInputInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "EposManager/DigitalInputInfo";
  }

  static const char* value(const  ::EposManager::DigitalInputInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::EposManager::DigitalInputInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This represents an input/output control structure for a Maxon motor attached to an EPOS 2 controller.  \n\
# The node_id is the node_id set on the epos controller itself\n\
# The state corresponds with the desired state of the digital outputs.\n\
\n\
uint16 node_id\n\
uint8 dIO_3_state\n\
uint8 dIO_4_state\n\
time stamp\n\
\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::EposManager::DigitalInputInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::EposManager::DigitalInputInfo_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::EposManager::DigitalInputInfo_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.node_id);
    stream.next(m.dIO_3_state);
    stream.next(m.dIO_4_state);
    stream.next(m.stamp);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DigitalInputInfo_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::EposManager::DigitalInputInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::EposManager::DigitalInputInfo_<ContainerAllocator> & v) 
  {
    s << indent << "node_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.node_id);
    s << indent << "dIO_3_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dIO_3_state);
    s << indent << "dIO_4_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dIO_4_state);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EPOSMANAGER_MESSAGE_DIGITALINPUTINFO_H

