"""autogenerated by genpy from EposManager/DigitalInputInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class DigitalInputInfo(genpy.Message):
  _md5sum = "0d37fc0461947d1bf0b6618aa2efcf0a"
  _type = "EposManager/DigitalInputInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# This represents an input/output control structure for a Maxon motor attached to an EPOS 2 controller.  
# The node_id is the node_id set on the epos controller itself
# The state corresponds with the desired state of the digital outputs.

uint16 node_id
uint8 dIO_3_state
uint8 dIO_4_state
time stamp





"""
  __slots__ = ['node_id','dIO_3_state','dIO_4_state','stamp']
  _slot_types = ['uint16','uint8','uint8','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       node_id,dIO_3_state,dIO_4_state,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DigitalInputInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.node_id is None:
        self.node_id = 0
      if self.dIO_3_state is None:
        self.dIO_3_state = 0
      if self.dIO_4_state is None:
        self.dIO_4_state = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.node_id = 0
      self.dIO_3_state = 0
      self.dIO_4_state = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_H2B2I.pack(_x.node_id, _x.dIO_3_state, _x.dIO_4_state, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.node_id, _x.dIO_3_state, _x.dIO_4_state, _x.stamp.secs, _x.stamp.nsecs,) = _struct_H2B2I.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_H2B2I.pack(_x.node_id, _x.dIO_3_state, _x.dIO_4_state, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.node_id, _x.dIO_3_state, _x.dIO_4_state, _x.stamp.secs, _x.stamp.nsecs,) = _struct_H2B2I.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_H2B2I = struct.Struct("<H2B2I")
