"""autogenerated by genpy from EposManager/GroupDigitalInputInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import EposManager.msg

class GroupDigitalInputInfo(genpy.Message):
  _md5sum = "6f71fe8202e041d98df9b82317e4d80b"
  _type = "EposManager/GroupDigitalInputInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# This represents the motor information of a group of motors

DigitalInputInfo[] io_group

================================================================================
MSG: EposManager/DigitalInputInfo
# This represents an input/output control structure for a Maxon motor attached to an EPOS 2 controller.  
# The node_id is the node_id set on the epos controller itself
# The state corresponds with the desired state of the digital outputs.

uint16 node_id
uint8 dIO_3_state
uint8 dIO_4_state
time stamp





"""
  __slots__ = ['io_group']
  _slot_types = ['EposManager/DigitalInputInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       io_group

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GroupDigitalInputInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.io_group is None:
        self.io_group = []
    else:
      self.io_group = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.io_group)
      buff.write(_struct_I.pack(length))
      for val1 in self.io_group:
        _x = val1
        buff.write(_struct_H2B.pack(_x.node_id, _x.dIO_3_state, _x.dIO_4_state))
        _v1 = val1.stamp
        _x = _v1
        buff.write(_struct_2I.pack(_x.secs, _x.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.io_group is None:
        self.io_group = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.io_group = []
      for i in range(0, length):
        val1 = EposManager.msg.DigitalInputInfo()
        _x = val1
        start = end
        end += 4
        (_x.node_id, _x.dIO_3_state, _x.dIO_4_state,) = _struct_H2B.unpack(str[start:end])
        _v2 = val1.stamp
        _x = _v2
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _struct_2I.unpack(str[start:end])
        self.io_group.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.io_group)
      buff.write(_struct_I.pack(length))
      for val1 in self.io_group:
        _x = val1
        buff.write(_struct_H2B.pack(_x.node_id, _x.dIO_3_state, _x.dIO_4_state))
        _v3 = val1.stamp
        _x = _v3
        buff.write(_struct_2I.pack(_x.secs, _x.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.io_group is None:
        self.io_group = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.io_group = []
      for i in range(0, length):
        val1 = EposManager.msg.DigitalInputInfo()
        _x = val1
        start = end
        end += 4
        (_x.node_id, _x.dIO_3_state, _x.dIO_4_state,) = _struct_H2B.unpack(str[start:end])
        _v4 = val1.stamp
        _x = _v4
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _struct_2I.unpack(str[start:end])
        self.io_group.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I = struct.Struct("<2I")
_struct_H2B = struct.Struct("<H2B")
